In [19]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as f
import numpy as np
import pandas as pd

spark = SparkSession\
    .builder\
    .appName("Python example")\
    .getOrCreate()

In [20]:
rdd = spark.sparkContext.parallelize([
    (1, 2., 'string1', date(2000,1,1), datetime(2000, 1, 1, 12, 0)),
    (10, 20., 'string10', date(2001,1,1), datetime(2000, 1, 1, 13, 0)),
    (100, 200., 'string100', date(2002,1,1), datetime(2000, 1, 1, 14, 0))
])

df = spark.createDataFrame(rdd, schema=['a', 'b', 'c', 'd', 'e'])
df

NameError: name 'date' is not defined

In [9]:
df = spark.createDataFrame([
    ['red', 'banana', 1, 10], ['purple', 'banana', 2, 20], ['white', 'carrot', 3, 30],
    ['blue', 'banana', 4, 40], ['green', 'grape', 5, 50], ['blue', 'carrot', 6, 60],
    ['red', 'banana', 7, 70], ['red', 'grape', 8, 80], ['white', 'banana', 9, 90],
],  schema=['color', 'fruit', 'v1', 'v2'])

df.show()

+------+------+---+---+
| color| fruit| v1| v2|
+------+------+---+---+
|   red|banana|  1| 10|
|purple|banana|  2| 20|
| white|carrot|  3| 30|
|  blue|banana|  4| 40|
| green| grape|  5| 50|
|  blue|carrot|  6| 60|
|   red|banana|  7| 70|
|   red| grape|  8| 80|
| white|banana|  9| 90|
+------+------+---+---+

In [10]:
df.groupby("color").avg().show()

+------+-----------------+------------------+
| color|          avg(v1)|           avg(v2)|
+------+-----------------+------------------+
| green|              5.0|              50.0|
|purple|              2.0|              20.0|
| white|              6.0|              60.0|
|   red|5.333333333333333|53.333333333333336|
|  blue|              5.0|              50.0|
+------+-----------------+------------------+

In [44]:
data = np.random.randint(1000, size=250)

pandas_df = pd.DataFrame(data, columns=['numbers'])

df = spark.createDataFrame(pandas_df)
df.select(f.reverse(df.numbers)).collect()

[Row(reverse(numbers)='333'),
 Row(reverse(numbers)='494'),
 Row(reverse(numbers)='816'),
 Row(reverse(numbers)='086'),
 Row(reverse(numbers)='541'),
 Row(reverse(numbers)='276'),
 Row(reverse(numbers)='929'),
 Row(reverse(numbers)='946'),
 Row(reverse(numbers)='466'),
 Row(reverse(numbers)='348'),
 Row(reverse(numbers)='186'),
 Row(reverse(numbers)='205'),
 Row(reverse(numbers)='476'),
 Row(reverse(numbers)='835'),
 Row(reverse(numbers)='853'),
 Row(reverse(numbers)='73'),
 Row(reverse(numbers)='812'),
 Row(reverse(numbers)='438'),
 Row(reverse(numbers)='817'),
 Row(reverse(numbers)='482'),
 Row(reverse(numbers)='952'),
 Row(reverse(numbers)='528'),
 Row(reverse(numbers)='749'),
 Row(reverse(numbers)='391'),
 Row(reverse(numbers)='298'),
 Row(reverse(numbers)='002'),
 Row(reverse(numbers)='858'),
 Row(reverse(numbers)='389'),
 Row(reverse(numbers)='832'),
 Row(reverse(numbers)='169'),
 Row(reverse(numbers)='488'),
 Row(reverse(numbers)='957'),
 Row(reverse(numbers)='095'),
 Row(reverse(numbers)='987'),
 Row(reverse(numbers)='476'),
 Row(reverse(numbers)='513'),
 Row(reverse(numbers)='23'),
 Row(reverse(numbers)='766'),
 Row(reverse(numbers)='449'),
 Row(reverse(numbers)='639'),
 Row(reverse(numbers)='817'),
 Row(reverse(numbers)='606'),
 Row(reverse(numbers)='699'),
 Row(reverse(numbers)='274'),
 Row(reverse(numbers)='915'),
 Row(reverse(numbers)='12'),
 Row(reverse(numbers)='313'),
 Row(reverse(numbers)='001'),
 Row(reverse(numbers)='352'),
 Row(reverse(numbers)='793'),
 Row(reverse(numbers)='066'),
 Row(reverse(numbers)='027'),
 Row(reverse(numbers)='764'),
 Row(reverse(numbers)='742'),
 Row(reverse(numbers)='302'),
 Row(reverse(numbers)='541'),
 Row(reverse(numbers)='269'),
 Row(reverse(numbers)='967'),
 Row(reverse(numbers)='476'),
 Row(reverse(numbers)='176'),
 Row(reverse(numbers)='092'),
 Row(reverse(numbers)='325'),
 Row(reverse(numbers)='958'),
 Row(reverse(numbers)='027'),
 Row(reverse(numbers)='543'),
 Row(reverse(numbers)='441'),
 Row(reverse(numbers)='812'),
 Row(reverse(numbers)='122'),
 Row(reverse(numbers)='564'),
 Row(reverse(numbers)='777'),
 Row(reverse(numbers)='591'),
 Row(reverse(numbers)='481'),
 Row(reverse(numbers)='632'),
 Row(reverse(numbers)='713'),
 Row(reverse(numbers)='84'),
 Row(reverse(numbers)='968'),
 Row(reverse(numbers)='19'),
 Row(reverse(numbers)='256'),
 Row(reverse(numbers)='134'),
 Row(reverse(numbers)='396'),
 Row(reverse(numbers)='478'),
 Row(reverse(numbers)='445'),
 Row(reverse(numbers)='578'),
 Row(reverse(numbers)='603'),
 Row(reverse(numbers)='389'),
 Row(reverse(numbers)='799'),
 Row(reverse(numbers)='27'),
 Row(reverse(numbers)='148'),
 Row(reverse(numbers)='243'),
 Row(reverse(numbers)='84'),
 Row(reverse(numbers)='075'),
 Row(reverse(numbers)='027'),
 Row(reverse(numbers)='212'),
 Row(reverse(numbers)='429'),
 Row(reverse(numbers)='613'),
 Row(reverse(numbers)='397'),
 Row(reverse(numbers)='52'),
 Row(reverse(numbers)='169'),
 Row(reverse(numbers)='376'),
 Row(reverse(numbers)='726'),
 Row(reverse(numbers)='703'),
 Row(reverse(numbers)='938'),
 Row(reverse(numbers)='846'),
 Row(reverse(numbers)='419'),
 Row(reverse(numbers)='287'),
 Row(reverse(numbers)='782'),
 Row(reverse(numbers)='894'),
 Row(reverse(numbers)='391'),
 Row(reverse(numbers)='997'),
 Row(reverse(numbers)='367'),
 Row(reverse(numbers)='588'),
 Row(reverse(numbers)='114'),
 Row(reverse(numbers)='244'),
 Row(reverse(numbers)='099'),
 Row(reverse(numbers)='41'),
 Row(reverse(numbers)='49'),
 Row(reverse(numbers)='801'),
 Row(reverse(numbers)='537'),
 Row(reverse(numbers)='331'),
 Row(reverse(numbers)='462'),
 Row(reverse(numbers)='205'),
 Row(reverse(numbers)='709'),
 Row(reverse(numbers)='166'),
 Row(reverse(numbers)='858'),
 Row(reverse(numbers)='773'),
 Row(reverse(numbers)='305'),
 Row(reverse(numbers)='341'),
 Row(reverse(numbers)='676'),
 Row(reverse(numbers)='002'),
 Row(reverse(numbers)='079'),
 Row(reverse(numbers)='498'),
 Row(reverse(numbers)='517'),
 Row(reverse(numbers)='422'),
 Row(reverse(numbers)='133'),
 Row(reverse(numbers)='71'),
 Row(reverse(numbers)='506'),
 Row(reverse(numbers)='704'),
 Row(reverse(numbers)='258'),
 Row(reverse(numbers)='135'),
 Row(reverse(numbers)='987'),
 Row(reverse(numbers)='562'),
 Row(reverse(numbers)='343'),
 Row(reverse(numbers)='503'),
 Row(reverse(numbers)='206'),
 Row(reverse(numbers)='502'),
 Row(reverse(numbers)='315'),
 Row(reverse(numbers)='902'),
 Row(reverse(numbers)='721'),
 Row(reverse(numbers)='783'),
 Row(reverse(numbers)='521'),
 Row(reverse(numbers)='442'),
 Row(reverse(numbers)='103'),
 Row(reverse(numbers)='052'),
 Row(reverse(numbers)='486'),
 Row(reverse(numbers)='32'),
 Row(reverse(numbers)='703'),
 Row(reverse(numbers)='658'),
 Row(reverse(numbers)='438'),
 Row(reverse(numbers)='68'),
 Row(reverse(numbers)='279'),
 Row(reverse(numbers)='957'),
 Row(reverse(numbers)='053'),
 Row(reverse(numbers)='614'),
 Row(reverse(numbers)='424'),
 Row(reverse(numbers)='879'),
 Row(reverse(numbers)='283'),
 Row(reverse(numbers)='875'),
 Row(reverse(numbers)='428'),
 Row(reverse(numbers)='214'),
 Row(reverse(numbers)='229'),
 Row(reverse(numbers)='385'),
 Row(reverse(numbers)='301'),
 Row(reverse(numbers)='927'),
 Row(reverse(numbers)='324'),
 Row(reverse(numbers)='605'),
 Row(reverse(numbers)='054'),
 Row(reverse(numbers)='321'),
 Row(reverse(numbers)='317'),
 Row(reverse(numbers)='948'),
 Row(reverse(numbers)='57'),
 Row(reverse(numbers)='268'),
 Row(reverse(numbers)='041'),
 Row(reverse(numbers)='648'),
 Row(reverse(numbers)='525'),
 Row(reverse(numbers)='708'),
 Row(reverse(numbers)='031'),
 Row(reverse(numbers)='417'),
 Row(reverse(numbers)='716'),
 Row(reverse(numbers)='099'),
 Row(reverse(numbers)='101'),
 Row(reverse(numbers)='021'),
 Row(reverse(numbers)='372'),
 Row(reverse(numbers)='507'),
 Row(reverse(numbers)='756'),
 Row(reverse(numbers)='691'),
 Row(reverse(numbers)='023'),
 Row(reverse(numbers)='723'),
 Row(reverse(numbers)='062'),
 Row(reverse(numbers)='357'),
 Row(reverse(numbers)='664'),
 Row(reverse(numbers)='057'),
 Row(reverse(numbers)='993'),
 Row(reverse(numbers)='708'),
 Row(reverse(numbers)='519'),
 Row(reverse(numbers)='966'),
 Row(reverse(numbers)='78'),
 Row(reverse(numbers)='394'),
 Row(reverse(numbers)='686'),
 Row(reverse(numbers)='39'),
 Row(reverse(numbers)='059'),
 Row(reverse(numbers)='57'),
 Row(reverse(numbers)='361'),
 Row(reverse(numbers)='016'),
 Row(reverse(numbers)='045'),
 Row(reverse(numbers)='286'),
 Row(reverse(numbers)='344'),
 Row(reverse(numbers)='502'),
 Row(reverse(numbers)='3'),
 Row(reverse(numbers)='577'),
 Row(reverse(numbers)='014'),
 Row(reverse(numbers)='871'),
 Row(reverse(numbers)='484'),
 Row(reverse(numbers)='711'),
 Row(reverse(numbers)='845'),
 Row(reverse(numbers)='515'),
 Row(reverse(numbers)='041'),
 Row(reverse(numbers)='388'),
 Row(reverse(numbers)='058'),
 Row(reverse(numbers)='422'),
 Row(reverse(numbers)='684'),
 Row(reverse(numbers)='589'),
 Row(reverse(numbers)='429'),
 Row(reverse(numbers)='605'),
 Row(reverse(numbers)='256'),
 Row(reverse(numbers)='214'),
 Row(reverse(numbers)='584'),
 Row(reverse(numbers)='034'),
 Row(reverse(numbers)='265'),
 Row(reverse(numbers)='478'),
 Row(reverse(numbers)='1'),
 Row(reverse(numbers)='644'),
 Row(reverse(numbers)='938'),
 Row(reverse(numbers)='772'),
 Row(reverse(numbers)='745'),
 Row(reverse(numbers)='205'),
 Row(reverse(numbers)='063'),
 Row(reverse(numbers)='174'),
 Row(reverse(numbers)='984'),
 Row(reverse(numbers)='193'),
 Row(reverse(numbers)='152')]